# Generated by Django 4.1 on 2022-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='是否已完成'),
        ),
    ]
