# Generated by Django 4.1 on 2022-08-08 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('target', models.PositiveIntegerField(verbose_name='目标')),
                ('finish_at', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '目标',
                'verbose_name_plural': '目标',
            },
        ),
        migrations.CreateModel(
            name='StockAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('name', models.CharField(max_length=8, verbose_name='证券公司名称')),
                ('number', models.CharField(max_length=16, verbose_name='账户号码')),
                ('account', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '股票账户',
                'verbose_name_plural': '股票账户',
            },
        ),
        migrations.CreateModel(
            name='MonetaryFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('name', models.CharField(max_length=64, verbose_name='名字')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '货币基金',
                'verbose_name_plural': '货币基金',
            },
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('card_id', models.IntegerField(verbose_name='卡号')),
                ('bank', models.CharField(max_length=32, verbose_name='银行')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '借记卡',
                'verbose_name_plural': '借记卡',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('card_id', models.IntegerField(verbose_name='卡号')),
                ('bank', models.CharField(max_length=32, verbose_name='银行')),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='账单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '信用卡',
                'verbose_name_plural': '信用卡',
            },
        ),
        migrations.CreateModel(
            name='AppBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('app_name', models.PositiveSmallIntegerField(choices=[(0, '微信'), (1, '支付宝')], verbose_name='app名字')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '应用余额',
                'verbose_name_plural': '应用余额',
            },
        ),
        migrations.CreateModel(
            name='Accumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='创建日期')),
                ('region', models.CharField(max_length=16, verbose_name='地区')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公积金',
                'verbose_name_plural': '公积金',
            },
        ),
    ]
